name: browserslist
on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  TITLE: ${{ github.event.pull_request.title }}
  COMMIT_MSG: ${{ github.event.head_commit.message }}

jobs:
  pipeline:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: ['16.x']
        os: ['ubuntu-latest']

    steps:

      - name: Clone repository
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - run: echo "Checking commit $COMMIT_MSG at $TITLE

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install npm dependencies
        id: install
        run: |
         npm install
         echo "::set-output name=install::nodejs"
      - name: Run test
        run: npm run test
        id: test

      - name: Configure git
        run: |
            git config --global user.email "action@github.com"
            git config --global user.name "GitHub Action"
      - name: Update caniuse database and create PR if applies
        uses: c2corg/browserslist-update-action@v1
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: browserslist-update
            commit_message: "build: update browserslist db"
            title: "build: update browserslist db"
            body: Auto-generated by [browserslist-update-action](https://github.com/c2corg/browserslist-update-action/)
